name: Build and Deploy AuroraMax GameHack Linux

# Triggers for the workflow
on:
  schedule:
    - cron: "0 7 * * *"  # 7 AM UTC everyday
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'  # Ignore changes to README.md
  pull_request:
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy Custom Image
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for compatibility
    permissions:
      contents: read  # Read repository contents
      packages: write  # Write to GitHub Container Registry (GHCR)
      id-token: write  # Write OIDC token for signing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the repository code

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@v7  # Remove unnecessary software to free up space

      - name: Build and Push Custom Image
        uses: blue-build/github-action@v1.6  # Use BlueBuild GitHub Action for building custom images
        with:
          recipe: recipe.yml  # Recipe file for the custom image
          signing_secret: ${{ secrets.SIGNING_SECRET }}  # Secret for cosign signing
          registry_token: ${{ github.token }}  # Token for GHCR authentication
          pr_event_number: ${{ github.event.number }}  # Tag images pushed from pull requests
          registry: ghcr.io  # Container registry (GitHub Container Registry)
          registry_namespace: ${{ github.repository_owner }}  # Namespace for the registry (repository owner)
